export const ACTION_TYPES ={
    CHANGE_INPUT: "CHANGE_INPUT",
    ADD_GENRE : "ADD_GENRE",
    SEARCH : "SEARCH",
    SEARCH_AGAIN: "SEARCH_AGAIN",
    TOGGLE_SEARCH_HIST: "TOGGLE_SEARCH_HIST",
    DELETE_SEARCH: "DELETE_SEARCH",
    CLEAR_HIST: "CLEAR_HIST",
    GET_CART_SIZE: "GET_CART_SIZE",
    INCREASE_CART_SIZE: "INCREASE_CART_SIZE"
}